const pptxgen = require('pptxgenjs');
const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const OUT = path.join(ROOT, 'master-package');
fs.mkdirSync(OUT, { recursive: true });

const C = { burgundy:'7A2036', blush:'FBEEE6', gold:'C9A227', cream:'FFF9F5', plum:'3A1420', ink:'2A2426', white:'FFFFFF', soft:'F5DED9', green:'2F725F' };
const F = { head:'Georgia', body:'Aptos' };
const IMG = {
  founder:path.join(ROOT,'ads-with-her','02-founder-introduction.png'),
  offer:path.join(ROOT,'ads-with-her','01-first-visit-offer.png'),
  booking:path.join(ROOT,'ads-with-her','03-whatsapp-booking-story.png'),
  concept:path.join(ROOT,'concept-board-blush-boutique.png')
};

function addBase(slide, title, kicker='NAILS WITH LOVE BY YESENIA') {
  slide.background = { color:C.cream };
  slide.addText(kicker,{x:.55,y:.25,w:6.5,h:.22,fontFace:F.body,fontSize:8,bold:true,color:C.gold,charSpacing:1.4,margin:0});
  slide.addText(title,{x:.55,y:.55,w:8.8,h:.55,fontFace:F.head,fontSize:25,bold:true,color:C.burgundy,margin:0,breakLine:false});
  slide.addShape('line',{x:.55,y:1.18,w:8.9,h:0,line:{color:C.gold,width:1}});
}
function footer(slide, n, label='Master presentation') {
  slide.addText(label,{x:.55,y:7.18,w:3.4,h:.16,fontFace:F.body,fontSize:7,color:'776B70',margin:0});
  slide.addText(String(n).padStart(2,'0'),{x:9.4,y:7.15,w:.35,h:.18,fontFace:F.body,fontSize:8,bold:true,color:C.burgundy,align:'right',margin:0});
}
function addBullets(slide, items, x,y,w,h, size=15) {
  const runs=[];
  items.forEach((t,i)=>{ runs.push({text:t,options:{bullet:{indent:14},breakLine:i<items.length-1}}); });
  slide.addText(runs,{x,y,w,h,fontFace:F.body,fontSize:size,color:C.ink,breakLine:false,paraSpaceAfterPt:9,margin:.06, valign:'top'});
}
function addImage(slide, file, x,y,w,h) { if(fs.existsSync(file)) slide.addImage({path:file,x,y,w,h}); }
function pill(slide,text,x,y,w,fill=C.burgundy,color=C.white){slide.addShape('roundRect',{x,y,w,h:.38,rectRadius:.08,fill:{color:fill},line:{color:fill}});slide.addText(text,{x:x+.05,y:y+.07,w:w-.1,h:.18,fontFace:F.body,fontSize:10,bold:true,color,align:'center',margin:0});}
function metric(slide,label,value,x,y,w){slide.addShape('roundRect',{x,y,w,h:.9,fill:{color:C.blush},line:{color:'E9CAC5',width:1}});slide.addText(value,{x:x+.12,y:y+.13,w:w-.24,h:.3,fontFace:F.head,fontSize:20,bold:true,color:C.burgundy,align:'center',margin:0});slide.addText(label,{x:x+.08,y:y+.53,w:w-.16,h:.18,fontFace:F.body,fontSize:8.5,color:C.ink,align:'center',margin:0});}

function newDeck(){const p=new pptxgen();p.layout='LAYOUT_WIDE';p.author='Nails with Love by Yesenia';p.subject='Business and marketing presentation';p.title='Nails with Love by Yesenia';p.company='ACool Ecosystem';p.lang='es-CO';p.theme={headFontFace:F.head,bodyFontFace:F.body,lang:'es-CO'};p.defineSlideMaster({title:'MASTER',background:{color:C.cream},objects:[]});return p;}

async function buildMaster(){
 const p=newDeck(); let s,n=0;
 s=p.addSlide('MASTER');n++;s.background={color:C.burgundy};s.addText('NAILS WITH LOVE',{x:.75,y:.85,w:6.4,h:.55,fontFace:F.head,fontSize:32,bold:true,color:C.white,margin:0});s.addText('by Yesenia',{x:.75,y:1.47,w:4,h:.45,fontFace:F.head,fontSize:24,italic:true,color:C.gold,margin:0});s.addText('Marca · Servicios · Ventas · WhatsApp · Crecimiento',{x:.75,y:2.15,w:5.5,h:.35,fontFace:F.body,fontSize:15,color:C.white,margin:0});pill(s,'UÑAS A DOMICILIO EN CALI',.75,2.75,2.9,C.gold,C.plum);addImage(s,IMG.founder,7.25,.35,5.2,6.8);s.addText('Presentación maestra · Julio 2026',{x:.75,y:6.6,w:4,h:.25,fontFace:F.body,fontSize:10,color:'EAD6D9',margin:0});
 s=p.addSlide('MASTER');n++;addBase(s,'La oportunidad');addBullets(s,['Clientas que valoran comodidad, privacidad y ahorro de tiempo.','Servicio móvil con inversión inicial menor que un salón tradicional.','Reservas directas por WhatsApp y contenido social como motor de demanda.','Posicionamiento personal: la clienta conoce a Yesenia, no a una marca genérica.'],.65,1.45,5.5,3.5,17);addImage(s,IMG.offer,7.15,1.35,3.25,5.05);metric(s,'Oferta de entrada','COP $55.000',.75,5.35,1.8);metric(s,'Servicio principal','A domicilio',2.75,5.35,1.8);metric(s,'Mercado inicial','Cali',4.75,5.35,1.5);footer(s,n);
 s=p.addSlide('MASTER');n++;addBase(s,'Identidad y promesa');s.addText('“Uñas hechas con amor, en la comodidad de tu hogar.”',{x:.8,y:1.55,w:6.4,h:.7,fontFace:F.head,fontSize:25,italic:true,color:C.burgundy,margin:0});addBullets(s,['Personal y cercana','Higiene visible','Precios claros','Diseños a tu estilo','Seguimiento después de la cita'],.85,2.65,4.8,2.8,16);addImage(s,IMG.concept,6.65,1.45,6.05,3.8);['7A2036','FBEEE6','C9A227','FFF9F5','3A1420'].forEach((c,i)=>s.addShape('rect',{x:7.0+i*.95,y:5.55,w:.78,h:.5,fill:{color:c},line:{color:c}}));footer(s,n);
 s=p.addSlide('MASTER');n++;addBase(s,'Menú propuesto en COP');const rows=[['Servicio','Precio propuesto'],['Primera cita boutique','$55.000'],['Manicure semipermanente','$80.000'],['Manicure premium','$105.000–125.000'],['Pedicure básica','$80.000'],['Combo manicure + pedicure','$150.000'],['Babyboomer / builder','$110.000'],['Gel X / soft gel','$120.000–145.000'],['Acrílico completo','$135.000–165.000']];s.addTable(rows,{x:.75,y:1.45,w:6.5,h:4.95,border:{color:'DEC7C8',width:.8},fill:C.white,color:C.ink,fontFace:F.body,fontSize:12,margin:.09,rowH:.5,bold:false,autoFit:false});s.addShape('roundRect',{x:7.65,y:1.65,w:4.7,h:2.0,fill:{color:C.blush},line:{color:C.gold,width:1}});s.addText('Regla comercial',{x:8.0,y:1.95,w:4,h:.3,fontFace:F.head,fontSize:20,bold:true,color:C.burgundy,align:'center',margin:0});s.addText('Publicar y cobrar en COP.\nCotizar arte, retiro, largo y desplazamiento antes del anticipo.',{x:8.05,y:2.45,w:3.9,h:.7,fontFace:F.body,fontSize:13,color:C.ink,align:'center',margin:0});s.addText('Precios sujetos a validación de costos, tiempo y zona.',{x:7.75,y:4.25,w:4.4,h:.55,fontFace:F.body,fontSize:11,italic:true,color:'766A6E',align:'center',margin:0});footer(s,n);
 s=p.addSlide('MASTER');n++;addBase(s,'Promociones que convierten');const cards=[['NUEVA CLIENTA','Primera cita boutique','$55.000'],['MÁS VENDIDO','Combo consentida','$150.000'],['REFERIDOS','Trae una amiga','$15.000 crédito'],['ENTRE SEMANA','Martes y miércoles','10% off']];cards.forEach((c,i)=>{let x=.7+(i%2)*6.15,y=1.45+Math.floor(i/2)*2.35;s.addShape('roundRect',{x,y,w:5.55,h:1.85,fill:{color:i===0?C.burgundy:C.white},line:{color:C.gold,width:1.2}});s.addText(c[0],{x:x+.25,y:y+.2,w:2.6,h:.2,fontFace:F.body,fontSize:9,bold:true,color:i===0?C.gold:C.burgundy,charSpacing:1,margin:0});s.addText(c[1],{x:x+.25,y:y+.62,w:3.8,h:.35,fontFace:F.head,fontSize:20,bold:true,color:i===0?C.white:C.plum,margin:0});s.addText(c[2],{x:x+.25,y:y+1.2,w:4.9,h:.25,fontFace:F.body,fontSize:14,bold:true,color:i===0?C.white:C.burgundy,margin:0});});footer(s,n);
 s=p.addSlide('MASTER');n++;addBase(s,'La experiencia de reserva');const steps=[['1','Descubrir','Instagram, referencia o QR'],['2','Cotizar','Servicio, diseño, barrio y retiro'],['3','Reservar','Horario + 50% de anticipo'],['4','Atender','Montaje limpio y servicio personal'],['5','Retener','Gracias, reseña y mantenimiento']];steps.forEach((a,i)=>{let x=.7+i*2.48;s.addShape('ellipse',{x:x+.55,y:1.75,w:.72,h:.72,fill:{color:i<3?C.burgundy:C.gold},line:{color:'FFFFFF',transparency:100}});s.addText(a[0],{x:x+.55,y:1.96,w:.72,h:.18,fontFace:F.body,fontSize:13,bold:true,color:C.white,align:'center',margin:0});s.addText(a[1],{x,y:2.65,w:1.8,h:.25,fontFace:F.head,fontSize:15,bold:true,color:C.burgundy,align:'center',margin:0});s.addText(a[2],{x:x-.08,y:3.05,w:2,h:.65,fontFace:F.body,fontSize:10.5,color:C.ink,align:'center',valign:'mid',margin:0});if(i<4)s.addShape('chevron',{x:x+1.85,y:1.98,w:.4,h:.28,fill:{color:C.soft},line:{color:C.soft}})});addImage(s,IMG.booking,4.65,4.1,2.05,3.0);s.addText('Automatizar lo repetitivo; mantener humana la conversación.',{x:7.1,y:4.65,w:4.8,h:.8,fontFace:F.head,fontSize:22,color:C.burgundy,margin:0});footer(s,n);
 s=p.addSlide('MASTER');n++;addBase(s,'Contenido y anuncios en español');addImage(s,IMG.founder,.7,1.35,3.15,4.9);addImage(s,IMG.offer,4.15,1.35,3.15,4.9);addImage(s,IMG.booking,7.6,1.35,2.76,4.9);s.addText('Presentación',{x:1.35,y:6.45,w:1.9,h:.2,fontFace:F.body,fontSize:9,bold:true,color:C.burgundy,align:'center',margin:0});s.addText('Oferta',{x:4.8,y:6.45,w:1.9,h:.2,fontFace:F.body,fontSize:9,bold:true,color:C.burgundy,align:'center',margin:0});s.addText('Reserva',{x:8.05,y:6.45,w:1.9,h:.2,fontFace:F.body,fontSize:9,bold:true,color:C.burgundy,align:'center',margin:0});footer(s,n);
 s=p.addSlide('MASTER');n++;addBase(s,'Plan de lanzamiento: 30 días');const weeks=[['SEMANA 1','Configurar WhatsApp, menú, políticas y cobertura.'],['SEMANA 2','Fotografiar 8–12 trabajos reales y publicar presentación.'],['SEMANA 3','Activar oferta de primera cita y programa de referidos.'],['SEMANA 4','Medir reservas, ticket, rebooking y ajustar horarios/precios.']];weeks.forEach((a,i)=>{let y=1.45+i*1.2;s.addText(a[0],{x:.8,y:y+.1,w:1.5,h:.2,fontFace:F.body,fontSize:9,bold:true,color:C.gold,margin:0});s.addShape('line',{x:2.25,y:y+.22,w:.6,h:0,line:{color:C.gold,width:2}});s.addText(a[1],{x:3,y,w:8.4,h:.45,fontFace:F.body,fontSize:15,color:C.ink,margin:0});});metric(s,'Meta inicial','20–30 conversaciones',1.2,6.0,2.55);metric(s,'Contenido','3–5 videos/semana',4.1,6.0,2.55);metric(s,'Seguimiento','100% de citas',7.0,6.0,2.55);footer(s,n);
 s=p.addSlide('MASTER');n++;addBase(s,'Indicadores de control');const ms=[['Consultas','Conversaciones nuevas'],['Conversión','Anticipos ÷ consultas'],['Asistencia','Citas realizadas ÷ anticipos'],['Ticket promedio','Ventas ÷ citas'],['Retención','Citas repetidas ÷ clientas'],['Referidos','Nuevas clientas por recomendación']];ms.forEach((a,i)=>{let x=.75+(i%3)*4.05,y=1.55+Math.floor(i/3)*2.05;s.addShape('roundRect',{x,y,w:3.55,h:1.45,fill:{color:C.white},line:{color:'E4CED0',width:1}});s.addText(a[0],{x:x+.18,y:y+.22,w:3.1,h:.28,fontFace:F.head,fontSize:17,bold:true,color:C.burgundy,margin:0});s.addText(a[1],{x:x+.18,y:y+.72,w:3.1,h:.3,fontFace:F.body,fontSize:11,color:C.ink,margin:0});});s.addText('La decisión de aumentar publicidad debe basarse en reservas rentables, no en “likes”.',{x:1.3,y:6.15,w:10.5,h:.45,fontFace:F.head,fontSize:19,italic:true,color:C.burgundy,align:'center',margin:0});footer(s,n);
 s=p.addSlide('MASTER');n++;addBase(s,'Materiales de punto de venta');addBullets(s,['Tarjeta de presentación con WhatsApp y QR.','Counter stand A4 con oferta, proceso y CTA.','Menú digital para WhatsApp Business.','Historias destacadas: Servicios, Precios, Diseños, Opiniones y Agenda.'],.8,1.55,5.4,3.1,17);s.addShape('rect',{x:7.2,y:1.45,w:4.4,h:5.4,fill:{color:C.white},line:{color:C.gold,width:1.5}});s.addText('AGENDA TU CITA',{x:7.65,y:1.85,w:3.5,h:.5,fontFace:F.head,fontSize:24,bold:true,color:C.burgundy,align:'center',margin:0});s.addText('Uñas hechas con amor,\nen la comodidad de tu hogar.',{x:7.65,y:2.65,w:3.5,h:.7,fontFace:F.body,fontSize:14,color:C.ink,align:'center',margin:0});s.addShape('rect',{x:8.35,y:3.65,w:2.1,h:2.1,fill:{color:C.blush},line:{color:C.burgundy,width:1,dash:'dash'}});s.addText('QR\nWHATSAPP',{x:8.5,y:4.3,w:1.8,h:.5,fontFace:F.body,fontSize:13,bold:true,color:C.burgundy,align:'center',margin:0});footer(s,n);
 s=p.addSlide('MASTER');n++;addBase(s,'Próximas decisiones');addBullets(s,['Confirmar número de WhatsApp (+57), Instagram y barrios de cobertura.','Validar precios con costos reales de producto, tiempo y transporte.','Confirmar horarios, medios de pago y política de reprogramación.','Sustituir el QR placeholder por un enlace wa.me probado.','Usar fotografías reales de trabajos terminados para prueba social.'],.9,1.5,7.5,3.6,18);pill(s,'LISTA PARA PERSONALIZAR Y LANZAR',3.9,5.8,5.0,C.burgundy,C.white);footer(s,n);
 await p.writeFile({fileName:path.join(OUT,'Nails-with-Love-Master-Presentation.pptx')});
}

async function buildBank(){
 const p=newDeck(); let s,n=0; const label='Presentación para bancos y aliados';
 s=p.addSlide('MASTER');n++;s.background={color:C.plum};s.addText('NAILS WITH LOVE',{x:.8,y:1.05,w:6.5,h:.6,fontFace:F.head,fontSize:34,bold:true,color:C.white,margin:0});s.addText('by Yesenia',{x:.8,y:1.75,w:4,h:.4,fontFace:F.head,fontSize:24,italic:true,color:C.gold,margin:0});s.addText('Plan de negocio · Servicio móvil de uñas en Cali',{x:.8,y:2.55,w:5.8,h:.4,fontFace:F.body,fontSize:17,color:C.white,margin:0});addImage(s,IMG.founder,7.35,.4,4.9,6.6);s.addText('Documento de conversación — cifras ilustrativas sujetas a validación',{x:.8,y:6.55,w:5.8,h:.25,fontFace:F.body,fontSize:9,color:'E4CED0',margin:0});
 s=p.addSlide('MASTER');n++;addBase(s,'Resumen del negocio','PLAN DE NEGOCIO');addBullets(s,['Emprendimiento personal de manicure, pedicure y extensiones a domicilio.','Mercado inicial: mujeres en Cali que buscan comodidad y atención personalizada.','Canal de ventas: WhatsApp; adquisición por Instagram, TikTok, referidos y alianzas.','Modelo liviano: equipo móvil, inventario controlado y citas con anticipo.'],.7,1.45,6.2,3.5,17);metric(s,'Oferta de entrada','$55.000',7.5,1.6,2.0);metric(s,'Ticket meta','$95.000',9.8,1.6,2.0);metric(s,'Anticipo','50%',7.5,3.0,2.0);metric(s,'Zona inicial','Cali',9.8,3.0,2.0);s.addText('Diferenciador: marca personal + experiencia boutique en casa.',{x:7.3,y:4.65,w:4.7,h:.7,fontFace:F.head,fontSize:20,color:C.burgundy,align:'center',margin:0});footer(s,n,label);
 s=p.addSlide('MASTER');n++;addBase(s,'Problema, solución y cliente','PLAN DE NEGOCIO');const cols=[['PROBLEMA','Traslados, esperas y experiencias impersonales.'],['SOLUCIÓN','Yesenia lleva una experiencia organizada y personalizada al hogar.'],['CLIENTA','Mujeres con poco tiempo, eventos, movilidad limitada o preferencia por privacidad.']];cols.forEach((a,i)=>{let x=.65+i*4.15;s.addShape('roundRect',{x,y:1.6,w:3.75,h:3.85,fill:{color:i===1?C.burgundy:C.white},line:{color:C.gold,width:1.2}});s.addText(a[0],{x:x+.25,y:1.95,w:3.25,h:.25,fontFace:F.body,fontSize:10,bold:true,color:i===1?C.gold:C.burgundy,align:'center',margin:0});s.addText(a[1],{x:x+.35,y:2.65,w:3.05,h:1.7,fontFace:F.head,fontSize:20,color:i===1?C.white:C.plum,align:'center',valign:'mid',margin:0});});footer(s,n,label);
 s=p.addSlide('MASTER');n++;addBase(s,'Modelo de ingresos','PLAN DE NEGOCIO');addBullets(s,['Servicios individuales en COP.','Add-ons: arte, retiro, largo, repair y desplazamiento.','Combos que aumentan el ticket promedio.','Anticipo para reducir cancelaciones y proteger agenda.','Mantenimiento cada 2–3 semanas y referidos para recurrencia.'],.7,1.45,5.7,3.8,17);addImage(s,IMG.offer,7.35,1.35,3.4,5.25);footer(s,n,label);
 s=p.addSlide('MASTER');n++;addBase(s,'Supuestos financieros de trabajo','PLAN DE NEGOCIO');const arows=[['Supuesto','Escenario base'],['Ticket promedio','COP $95.000'],['Costo de productos','18% de ventas'],['Transporte promedio','COP $12.000 por cita'],['Comisiones de pago','1,5% de ventas'],['Marketing + operación fija','COP $550.000/mes'],['Citas/mes al estabilizar','40']];s.addTable(arows,{x:.75,y:1.45,w:7,h:4.85,border:{color:'DEC7C8',width:.8},fill:C.white,color:C.ink,fontFace:F.body,fontSize:13,margin:.1,rowH:.55});s.addText('Estos son supuestos ilustrativos. Antes de presentar una solicitud formal se deben sustituir por facturas, cotizaciones, extractos y registros reales.',{x:8.25,y:1.8,w:3.75,h:1.6,fontFace:F.head,fontSize:18,color:C.burgundy,align:'center',valign:'mid',margin:0});s.addShape('roundRect',{x:8.35,y:4.05,w:3.55,h:1.2,fill:{color:C.blush},line:{color:C.gold,width:1}});s.addText('Punto de equilibrio estimado\n≈ 9 citas/mes',{x:8.55,y:4.34,w:3.15,h:.6,fontFace:F.body,fontSize:15,bold:true,color:C.burgundy,align:'center',margin:0});footer(s,n,label);
 s=p.addSlide('MASTER');n++;addBase(s,'Escenarios mensuales','PLAN DE NEGOCIO');const scenarios=[['INICIAL','24 citas','$2,28 M','$1,00 M'],['BASE','40 citas','$3,80 M','$2,03 M'],['CRECIMIENTO','56 citas','$5,32 M','$3,06 M']];scenarios.forEach((a,i)=>{let x=.75+i*4.08;s.addShape('roundRect',{x,y:1.6,w:3.65,h:3.75,fill:{color:i===1?C.burgundy:C.white},line:{color:C.gold,width:1.3}});s.addText(a[0],{x:x+.2,y:1.95,w:3.25,h:.25,fontFace:F.body,fontSize:10,bold:true,color:i===1?C.gold:C.burgundy,align:'center',margin:0});s.addText(a[1],{x:x+.2,y:2.45,w:3.25,h:.35,fontFace:F.head,fontSize:23,bold:true,color:i===1?C.white:C.plum,align:'center',margin:0});s.addText('Ventas mensuales\n'+a[2],{x:x+.25,y:3.1,w:3.15,h:.65,fontFace:F.body,fontSize:14,color:i===1?C.white:C.ink,align:'center',margin:0});s.addText('Excedente operativo*\n'+a[3],{x:x+.25,y:4.05,w:3.15,h:.65,fontFace:F.body,fontSize:14,bold:true,color:i===1?C.white:C.burgundy,align:'center',margin:0});});s.addText('*Antes de remuneración de la propietaria, impuestos, deuda e inversiones. Basado en los supuestos de la diapositiva anterior.',{x:1.0,y:6.15,w:11,h:.35,fontFace:F.body,fontSize:9,color:'766A6E',align:'center',margin:0});footer(s,n,label);
 s=p.addSlide('MASTER');n++;addBase(s,'Uso propuesto de fondos','PLAN DE NEGOCIO');const uses=[['Equipo y esterilización','$2,2 M',26],['Inventario inicial','$1,8 M',21],['Maleta y mobiliario móvil','$1,2 M',14],['Marca, contenido y pauta','$1,3 M',15],['Capital de trabajo','$2,0 M',24]];uses.forEach((a,i)=>{let y=1.5+i*.9;s.addText(a[0],{x:.8,y:y+.08,w:3.4,h:.2,fontFace:F.body,fontSize:12,color:C.ink,margin:0});s.addText(a[1],{x:4.25,y:y+.08,w:1.2,h:.2,fontFace:F.body,fontSize:12,bold:true,color:C.burgundy,align:'right',margin:0});s.addShape('rect',{x:5.8,y:y+.04,w:a[2]*.16,h:.35,fill:{color:i%2?C.gold:C.burgundy},line:{color:'FFFFFF',transparency:100}});});s.addShape('roundRect',{x:8.75,y:1.8,w:3,h:2.2,fill:{color:C.blush},line:{color:C.gold,width:1.2}});s.addText('SOLICITUD INDICATIVA',{x:9.05,y:2.15,w:2.4,h:.25,fontFace:F.body,fontSize:9,bold:true,color:C.burgundy,align:'center',margin:0});s.addText('COP $8,5 M',{x:9.0,y:2.8,w:2.5,h:.45,fontFace:F.head,fontSize:27,bold:true,color:C.burgundy,align:'center',margin:0});s.addText('Ajustar después de cotizaciones reales.',{x:8.8,y:4.7,w:2.9,h:.5,fontFace:F.body,fontSize:11,italic:true,color:'766A6E',align:'center',margin:0});footer(s,n,label);
 s=p.addSlide('MASTER');n++;addBase(s,'Estrategia comercial','PLAN DE NEGOCIO');addBullets(s,['Lanzamiento con oferta de primera cita, sin devaluar el menú completo.','Contenido de procesos y resultados reales; consentimiento de imagen documentado.','Programa de referidos con crédito para la siguiente cita.','Alianzas con boutiques, estilistas, maquilladoras, gimnasios y eventos.','Seguimiento por WhatsApp para mantenimiento y recuperación de clientas.'],.75,1.5,6.25,4.3,17);addImage(s,IMG.booking,8.0,1.35,2.9,5.35);footer(s,n,label);
 s=p.addSlide('MASTER');n++;addBase(s,'Riesgos y controles','PLAN DE NEGOCIO');const risk=[['Cancelaciones','Anticipo, recordatorio y política clara.'],['Márgenes débiles','Costeo por servicio, zona y duración.'],['Dependencia de una persona','Agenda limitada, protocolos y fondo de emergencia.'],['Salud e higiene','Instrumental, desinfección y rechazo de condiciones sospechosas.'],['Demanda irregular','Referidos, alianzas, combos y días de baja demanda.'],['Datos insuficientes','Registro semanal de ventas, costos, citas y retención.']];risk.forEach((a,i)=>{let x=.7+(i%2)*6.15,y=1.45+Math.floor(i/2)*1.55;s.addText(a[0],{x,y,w:1.7,h:.25,fontFace:F.head,fontSize:14,bold:true,color:C.burgundy,margin:0});s.addText(a[1],{x:x+1.8,y,w:3.8,h:.45,fontFace:F.body,fontSize:11.5,color:C.ink,margin:0});});footer(s,n,label);
 s=p.addSlide('MASTER');n++;addBase(s,'Hitos de los primeros 12 meses','PLAN DE NEGOCIO');const milestones=[['0–3 meses','Validar menú, 20+ clientas, registro de costos.'],['4–6 meses','40 citas/mes, rebooking medido, 3 alianzas.'],['7–9 meses','Optimizar rutas y capacidad; evaluar apoyo operativo.'],['10–12 meses','Historial financiero, cartera recurrente y plan de expansión.']];milestones.forEach((a,i)=>{let x=.75+i*3.05;s.addShape('ellipse',{x:x+1.0,y:1.7,w:.55,h:.55,fill:{color:i<2?C.burgundy:C.gold},line:{color:C.white,transparency:100}});if(i<3)s.addShape('line',{x:x+1.55,y:1.98,w:2.5,h:0,line:{color:C.gold,width:2}});s.addText(a[0],{x,y:2.55,w:2.55,h:.35,fontFace:F.head,fontSize:16,bold:true,color:C.burgundy,align:'center',margin:0});s.addText(a[1],{x:x-.05,y:3.15,w:2.65,h:1.25,fontFace:F.body,fontSize:11.5,color:C.ink,align:'center',valign:'top',margin:0});});s.addText('Meta: construir un negocio documentado, rentable y financiable antes de asumir costos fijos de un local.',{x:1.0,y:5.7,w:11,h:.75,fontFace:F.head,fontSize:20,italic:true,color:C.burgundy,align:'center',margin:0});footer(s,n,label);
 s=p.addSlide('MASTER');n++;addBase(s,'Documentos que acompañan una solicitud','PLAN DE NEGOCIO');addBullets(s,['Cédula, RUT y registro mercantil si aplica.','Extractos bancarios y evidencia de ventas.','Cotizaciones de equipo, inventario y transporte.','Portafolio real, menú y políticas.','Proyección de flujo de caja actualizada.','Certificados de formación e higiene disponibles.'],.9,1.5,6.2,3.8,17);s.addShape('roundRect',{x:8.0,y:1.6,w:3.6,h:3.6,fill:{color:C.blush},line:{color:C.gold,width:1.2}});s.addText('La confianza financiera se construye con evidencia, no solo con diseño.',{x:8.45,y:2.3,w:2.7,h:1.7,fontFace:F.head,fontSize:22,color:C.burgundy,align:'center',valign:'mid',margin:0});footer(s,n,label);
 s=p.addSlide('MASTER');n++;s.background={color:C.burgundy};s.addText('Nails with Love by Yesenia',{x:1.0,y:1.25,w:7,h:.7,fontFace:F.head,fontSize:34,bold:true,color:C.white,margin:0});s.addText('Uñas hechas con amor, en la comodidad de tu hogar.',{x:1.0,y:2.2,w:7.2,h:.45,fontFace:F.head,fontSize:22,italic:true,color:C.gold,margin:0});s.addText('+57 310 848 6630  ·  @nailswithlove.yesenia  ·  CALI, COLOMBIA',{x:1.0,y:3.45,w:7.2,h:.3,fontFace:F.body,fontSize:14,color:C.white,margin:0});s.addShape('rect',{x:9.2,y:2.0,w:2.2,h:2.2,fill:{color:C.blush},line:{color:C.gold,width:1,dash:'dash'}});s.addText('QR\nWHATSAPP',{x:9.45,y:2.7,w:1.7,h:.55,fontFace:F.body,fontSize:14,bold:true,color:C.burgundy,align:'center',margin:0});s.addText('Gracias',{x:1.0,y:5.8,w:3,h:.4,fontFace:F.head,fontSize:24,color:C.white,margin:0});
 await p.writeFile({fileName:path.join(OUT,'Nails-with-Love-Bank-and-Partner-Presentation.pptx')});
}

function esc(s){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
async function renderSvg(name,w,h,svg){await sharp(Buffer.from(svg)).png().toFile(path.join(OUT,name));}
async function buildPrintAssets(){
 const style=`<style>.ser{font-family:Georgia,serif}.sans{font-family:Arial,sans-serif}</style>`;
 const front=`<svg xmlns="http://www.w3.org/2000/svg" width="1050" height="600">${style}<rect width="1050" height="600" fill="#7A2036"/><circle cx="920" cy="80" r="180" fill="#C9A227" opacity=".18"/><text x="75" y="180" class="ser" font-size="72" font-weight="700" fill="#FFF9F5">Nails with Love</text><text x="78" y="245" class="ser" font-size="40" font-style="italic" fill="#C9A227">by Yesenia</text><text x="78" y="350" class="sans" font-size="28" fill="#FFF9F5">Uñas a domicilio en Cali</text><text x="78" y="420" class="sans" font-size="24" fill="#F3DDE0">Uñas hechas con amor,</text><text x="78" y="455" class="sans" font-size="24" fill="#F3DDE0">en la comodidad de tu hogar.</text><path d="M820 370 C880 310 955 330 980 405 C915 450 850 450 820 370Z" fill="none" stroke="#C9A227" stroke-width="8"/><path d="M856 388 C885 362 925 365 945 401" fill="none" stroke="#C9A227" stroke-width="6"/></svg>`;
 const back=`<svg xmlns="http://www.w3.org/2000/svg" width="1050" height="600">${style}<rect width="1050" height="600" fill="#FFF9F5"/><rect x="0" y="0" width="1050" height="22" fill="#C9A227"/><text x="70" y="105" class="ser" font-size="42" font-weight="700" fill="#7A2036">Agenda tu cita</text><text x="70" y="165" class="sans" font-size="25" fill="#3A1420">Manicure · Pedicure · Acrílico · Gel X · Nail Art</text><text x="70" y="250" class="sans" font-size="27" font-weight="700" fill="#7A2036">WhatsApp</text><text x="70" y="292" class="sans" font-size="25" fill="#3A1420">+57 310 848 6630</text><text x="70" y="365" class="sans" font-size="27" font-weight="700" fill="#7A2036">Instagram</text><text x="70" y="407" class="sans" font-size="25" fill="#3A1420">@nailswithlove.yesenia</text><text x="70" y="500" class="sans" font-size="22" fill="#7A2036">Primera cita boutique desde COP $55.000</text><rect x="745" y="125" width="235" height="235" rx="20" fill="#FBEEE6" stroke="#7A2036" stroke-width="5" stroke-dasharray="14 10"/><text x="862" y="220" text-anchor="middle" class="sans" font-size="27" font-weight="700" fill="#7A2036">ESPACIO</text><text x="862" y="258" text-anchor="middle" class="sans" font-size="27" font-weight="700" fill="#7A2036">PARA QR</text><text x="862" y="408" text-anchor="middle" class="sans" font-size="20" fill="#3A1420">Escanea y agenda</text></svg>`;
 await renderSvg('business-card-front.png',1050,600,front); await renderSvg('business-card-back.png',1050,600,back);
 const stand=`<svg xmlns="http://www.w3.org/2000/svg" width="2480" height="3508">${style}<rect width="2480" height="3508" fill="#FFF9F5"/><rect x="0" y="0" width="2480" height="430" fill="#7A2036"/><text x="1240" y="170" text-anchor="middle" class="ser" font-size="150" font-weight="700" fill="#FFF9F5">Nails with Love</text><text x="1240" y="315" text-anchor="middle" class="ser" font-size="80" font-style="italic" fill="#C9A227">by Yesenia</text><text x="1240" y="610" text-anchor="middle" class="ser" font-size="125" font-weight="700" fill="#7A2036">TU PRIMERA CITA BOUTIQUE</text><text x="1240" y="760" text-anchor="middle" class="sans" font-size="70" fill="#3A1420">Manicure semipermanente + diseño sencillo</text><rect x="590" y="860" width="1300" height="300" rx="60" fill="#FBEEE6" stroke="#C9A227" stroke-width="8"/><text x="1240" y="1060" text-anchor="middle" class="ser" font-size="150" font-weight="700" fill="#7A2036">COP $55.000</text><text x="1240" y="1350" text-anchor="middle" class="ser" font-size="95" fill="#7A2036">Uñas hechas con amor,</text><text x="1240" y="1465" text-anchor="middle" class="ser" font-size="95" fill="#7A2036">en la comodidad de tu hogar.</text><g class="sans" font-size="62" fill="#3A1420"><text x="430" y="1750">✓ Atención personalizada</text><text x="430" y="1870">✓ Servicio a domicilio en Cali</text><text x="430" y="1990">✓ Reserva fácil por WhatsApp</text></g><rect x="790" y="2170" width="900" height="900" rx="45" fill="#FBEEE6" stroke="#7A2036" stroke-width="12" stroke-dasharray="30 20"/><text x="1240" y="2530" text-anchor="middle" class="sans" font-size="80" font-weight="700" fill="#7A2036">ESPACIO PARA QR</text><text x="1240" y="2640" text-anchor="middle" class="sans" font-size="60" fill="#3A1420">WhatsApp +57 310 848 6630</text><rect x="480" y="3190" width="1520" height="170" rx="85" fill="#7A2036"/><text x="1240" y="3300" text-anchor="middle" class="sans" font-size="75" font-weight="700" fill="#FFFFFF">ESCANEA Y AGENDA AHORA</text><text x="1240" y="3445" text-anchor="middle" class="sans" font-size="35" fill="#7A2036">Clientes nuevas · Retiro y desplazamiento fuera de zona no incluidos</text></svg>`;
 await renderSvg('counter-stand-A4.png',2480,3508,stand);
 const ad1=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350">${style}<rect width="1080" height="1350" fill="#FBEEE6"/><text x="70" y="160" class="ser" font-size="92" font-weight="700" fill="#7A2036">MANOS + PIES,</text><text x="70" y="270" class="ser" font-size="92" font-weight="700" fill="#7A2036">TODO LISTO</text><text x="70" y="370" class="sans" font-size="45" fill="#3A1420">Combo semipermanente a domicilio</text><circle cx="540" cy="740" r="270" fill="#FFF9F5" stroke="#C9A227" stroke-width="8"/><text x="540" y="700" text-anchor="middle" class="sans" font-size="45" fill="#7A2036">PRECIO ESPECIAL</text><text x="540" y="805" text-anchor="middle" class="ser" font-size="105" font-weight="700" fill="#7A2036">$150.000</text><text x="540" y="870" text-anchor="middle" class="sans" font-size="34" fill="#3A1420">COP</text><rect x="170" y="1080" width="740" height="120" rx="60" fill="#7A2036"/><text x="540" y="1158" text-anchor="middle" class="sans" font-size="47" font-weight="700" fill="#FFFFFF">AGENDA POR WHATSAPP</text><text x="540" y="1280" text-anchor="middle" class="sans" font-size="30" fill="#7A2036">Cali · Consulta cobertura y disponibilidad</text></svg>`;
 const ad2=`<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1350">${style}<rect width="1080" height="1350" fill="#7A2036"/><text x="540" y="150" text-anchor="middle" class="sans" font-size="35" font-weight="700" letter-spacing="6" fill="#C9A227">REFERIDOS</text><text x="540" y="320" text-anchor="middle" class="ser" font-size="100" font-weight="700" fill="#FFFFFF">BELLEZA ENTRE</text><text x="540" y="435" text-anchor="middle" class="ser" font-size="100" font-weight="700" fill="#FFFFFF">AMIGAS</text><path d="M280 640 C350 530 500 570 540 690 C580 570 730 530 800 640 C865 745 760 860 540 1010 C320 860 215 745 280 640Z" fill="#FBEEE6"/><text x="540" y="740" text-anchor="middle" class="sans" font-size="40" font-weight="700" fill="#7A2036">AMBAS RECIBEN</text><text x="540" y="845" text-anchor="middle" class="ser" font-size="92" font-weight="700" fill="#7A2036">$15.000 COP</text><text x="540" y="910" text-anchor="middle" class="sans" font-size="31" fill="#3A1420">de crédito para su próxima cita</text><rect x="185" y="1115" width="710" height="110" rx="55" fill="#C9A227"/><text x="540" y="1188" text-anchor="middle" class="sans" font-size="44" font-weight="700" fill="#3A1420">COMPARTE Y AGENDA</text><text x="540" y="1300" text-anchor="middle" class="sans" font-size="28" fill="#F4DDE1">Aplica cuando tu amiga nueva complete su cita</text></svg>`;
 await renderSvg('spanish-ad-combo.png',1080,1350,ad1);await renderSvg('spanish-ad-referral.png',1080,1350,ad2);
}

(async()=>{await buildPrintAssets();await buildMaster();await buildBank();console.log('Created',OUT);})().catch(e=>{console.error(e);process.exit(1)});
